#!/usr/bin/env bash
# HTTP fuzzing script - first attempt (note: not well tested!)

junk_data=$(head -c 10000 /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 1000)
http_data=$'GET / HTTP/1.1\r\nHost: localhost\r\nUser-Agent: fuzzing-tool\r\nX-Fuzz: '"$junk_data"$'\r\nConnection: close\r\n\r\n'
telnet localhost 80 <<<"$http_data"
